title: SSENFUMA GODFREY
logo: SSENFUMA GODFREY.jpg
description: Detail-oriented Data Analyst with expertise in transforming raw data into business actionable insights.
Skilled in SQL, Python, Excel and Visualization tools (Power BI and Tableau). 
Experienced in data cleaning, analyzing and interpreting datasets to support business decision-making. 
Strong knowledge of  statistical modeling.  I bridge the gap between technical analysis and commercial strategy.
show_downloads: true
theme: jekyll-theme-minimal
